name: build

env:
  ENV_LINUX: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v2
  ENV_WINDOWS: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOAMD64=v3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'
        cache: false

    - name: git clone
      run: |
        git clone --depth 1 https://github.com/juicity/juicity.git

    - name: go build
      run: | 
        cd juicity
        go env -w ${{ env.ENV_LINUX }}
        make juicity-server
        go env -w ${{ env.ENV_WINDOWS }}
        make juicity-client
        mv juicity-client juicity-client.exe

    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: juicity
        path: |
          juicity/juicity-server
          juicity/juicity-client.exe
